export const reducerCases = {
  SET_IS_VALID: "SET_IS_VALID",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_LOGOUT: "SET_LOGOUT",
  SET_USER: "SET_USER",
  SET_USER_AUTH: "SET_USER_AUTH",
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_PHONE: "SET_PHONE",
  SET_NAME: "SET_NAME",
  SET_BLOOD_GROUP: "SET_BLOOD_GROUP",
  SET_PROFILE_POPUP: "SET_PROFILE_POPUP",
};
